### ISSUE TITLE
タスク詳細画面

### ISSUE THREAD

**Issue by HayataTakagi** [enpitut2019/task-cabinet#114]
通知をタップされた時の遷移先が今はない状態

ダイアログにタスクの情報を表示する感じ？

**Comment by shuuji3** [comment]
ダイアログは文字数が限られていてすべての情報が表示できない可能性があるので、タップ後は当該タスクの詳細画面に遷移するのはどうでしょう。

**Comment by tmyksj** [comment]
今すべての情報が task に表示されているので、今のところ無理に作成する必要はなさそう？
（ description を追加できるようになると、必要になってきそうです。

**Comment by HayataTakagi** [comment]
どのタスクに対する通知だったのかが分かりにくいかもです
詳細画面作らないなら、該当タスクに表示箇所を飛ばすアンカー機能が必要になりますね、

**Comment by tmyksj** [comment]
あーなるほど。それだと必要そうですね。

**Comment by tmyksj** [comment]
url はこんな感じで大丈夫ですか？
```
/task/:id
```
