### ISSUE TITLE
PWA の導入

### ISSUE THREAD

**Issue by tmyksj** [enpitut2019/task-cabinet#55]
PWA を導入します。 `ng add @angular/pwa` くらい？　で導入できそうです。
参考: https://web.dev/creating-pwa-with-angular-cli/

あと、ビルド時に `--prod` オプションが必要みたいなので、デプロイコマンドを書き換えます。
参考: https://angular.jp/guide/service-worker-getting-started

**Comment by shuuji3** [comment]
Google Chrome Devtools > Application タブで Manifest の情報が表示できるので、正しくインストールできたかの確認ができるかもしれません。
