### ISSUE TITLE
init した段階のアプリを github.io で表示できるように設定する

### ISSUE THREAD

**Issue by shuuji3** [enpitut2019/task-cabinet#7]
## What

github.io ドメインで最低限見られるようにします。

## Why

enPiT のレビューではデプロイされた状態でなければ許されないからです。

**Comment by tmyksj** [comment]
引き受けます

**Comment by shuuji3** [comment]
#11 で Fix #7 と書くと、GitHub が自動的に Issue を紐付けてくれて、PR を merge するだけでこちらも自動で Close してくれるんですね。すごく便利。
