### ISSUE TITLE
CORSエラーでgithub.ioのアプリからタスクが追加できない

### ISSUE THREAD

**Issue by shuuji3** [enpitut2019/task-cabinet#97]
<https://enpitut2019.github.io/task-cabinet/add> でタスクを追加しようとすると、CORSのエラーが発生してタスクが追加できないようです。

<img width="494" alt="Screen Shot 2019-12-20 at 13 05 56" src="https://user-images.githubusercontent.com/1425259/71229851-7bbffe00-232a-11ea-9d05-ec4fd3f449ef.png">

ログインのリクエストは`200 OK`が返ってきて成功します。

**Comment by HayataTakagi** [comment]
https://enpit2019tkb.slack.com/archives/CLBGRUE79/p1576815391011000
